/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include "run/vss_android.h"
#ifndef _Included_tvs_ndk_NativeCode
#define _Included_tvs_ndk_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tvs_ndk_NativeCode

 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jstring JNICALL Java_tsv_com_vssandroid_NativeCode_vss(JNIEnv *, jobject,
		jstring, jint);
#ifdef __cplusplus
}
#endif
#endif
